services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    restart: always
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      DEL_PASWD: ${DEL_PASWD}
      TOKEN: ${TOKEN}
      ADMINS: ${ADMINS}
      PROXY_URL: ${PROXY_URL}
      DEV: ${DEV}

    depends_on:
      - postgres

volumes:
  postgres_data:
