services:
  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    restart: always
    volumes:
      - .:/app
    env_file:
      - bot.env
    networks:
      - default
      - shared_network

    depends_on:
      - postgres

volumes:
  postgres_data:


networks:
  default:
  shared_network:
    external: true
